name: Build toolchain GCC13

on: workflow_dispatch

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    name: ${{ matrix.model }}-${{ matrix.libc }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        model:
          - armv8
          - nanopi-r4s
          - nanopi-r5s
          - x86_64
        tag:
          - type: rc2
            version: openwrt-23.05
        libc:
          - musl
          - glibc

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Show system
      run: |
        lscpu
        free -h
        df -Th
        uname -a

    - name: Set release env
      run: |
        sudo mkdir -p /builder
        sudo chown -R runner.runner /builder
        echo WORKDIR="/builder" >> "$GITHUB_ENV"
        if [[ ${{ matrix.model }} == "null" ]]; then
          echo "release=false" >> "$GITHUB_ENV"
        fi

    - name: Free disk space
      run: |
        sudo rm -rf /etc/apt/sources.list.d
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo docker image prune -a -f
        sudo systemctl stop docker
        sudo snap set system refresh.retain=2
        sudo apt-get -y purge firefox clang* ghc* google* llvm* mono* mongo* mysql* php*
        sudo apt-get -y autoremove --purge
        sudo apt-get clean
        sudo rm -rf /etc/mysql /etc/php /usr/lib/jvm /usr/libexec/docker /usr/local /usr/src/* /var/lib/docker /var/lib/gems /var/lib/mysql /var/lib/snapd /etc/skel /opt/{microsoft,az,hostedtoolcache,cni,mssql-tools,pipx} /usr/share/{az*,dotnet,swift,miniconda,gradle*,java,kotlinc,ri,sbt} /root/{.sbt,.local,.npm}
        sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
        rm -rf ~/{.cargo,.dotnet,.rustup}
        df -Th

    - name: Build System Setup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison cmake g++ gawk gcc-multilib g++-multilib gettext git libfuse-dev libncurses5-dev libssl-dev python3 python3-pip python3-ply python3-distutils python3-pyelftools rsync unzip zlib1g-dev file wget subversion patch upx-ucl autoconf automake curl asciidoc binutils bzip2 lib32gcc-s1 libc6-dev-i386 uglifyjs msmtp texinfo libreadline-dev libglib2.0-dev xmlto libelf-dev libtool autopoint antlr3 gperf ccache swig coreutils haveged scons libpython3-dev rename qemu-utils
        sudo apt-get clean
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

    - name: Install LLVM
      run: |
        export PATH="/opt/clang/bin:$PATH"
        mkdir /opt/clang
        curl -LO https://github.com/sbwml/redhat-llvm-project/releases/download/18.1.6/clang-18.1.6-x86_64-redhat-linux.tar.xz --progress-bar
        sudo tar --strip-components=1 -C /opt/clang -xf clang-18.1.6-x86_64-redhat-linux.tar.xz
        rm -rf clang-18.1.6-x86_64-redhat-linux.tar.xz
        clang --version

    - name: Compile Toolchain
      working-directory: /builder
      run: |
        export PATH="/opt/clang/bin:$PATH"
        [ "${{ matrix.libc }}" = "glibc" ] && export USE_GLIBC=y
        BUILD_TOOLCHAIN=y ENABLE_LTO=y ENABLE_BPF=y USE_GCC13=y USE_MOLD=y bash <(curl -sS ${{ secrets.script_url_general }}) ${{ matrix.tag.type }} ${{ matrix.model }}

    - name: Create release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: ${{ matrix.tag.version }}
        allowUpdates: true
        tag: ${{ matrix.tag.version }}
        commit: main
        replacesArtifacts: true
        token: ${{ secrets.workflow_token }}
        artifacts: ${{ env.WORKDIR }}/openwrt/toolchain-cache/*.tar.gz
